"""specialized evaluators.

Revision ID: 142b8ab4f85d
Revises: 20260703_0006
Create Date: 2026-07-03 22:07:52.575136
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "142b8ab4f85d"
down_revision: str | None = "20260703_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_decision_findings_source_type", "decision_input_findings", type_="check")
    op.create_check_constraint(
        "ck_decision_findings_source_type",
        "decision_input_findings",
        "source_type IN ('FINANCIAL_EVALUATION', 'SPECIALIZED_EVALUATION', "
        "'SYNTHETIC', 'MISSING_ADAPTER')",
    )
    op.create_table(
        "specialized_evaluation_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("normalization_run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("force", sa.Boolean(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain IN ('LEGAL', 'EXPERIENCE', 'TECHNICAL', 'WORKFORCE', 'DOCUMENTARY', 'GUARANTEE', 'OPERATIONAL', 'ORGANIZATIONAL', 'RISK')",
            name="ck_specialized_jobs_domain",
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELLED')",
            name="ck_specialized_jobs_status",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_specialized_jobs_attempts"),
        sa.CheckConstraint("max_attempts > 0", name="ck_specialized_jobs_max_attempts"),
        sa.CheckConstraint("priority >= 0", name="ck_specialized_jobs_priority"),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["company_profile_snapshot_id"], ["company_profile_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["normalization_run_id"], ["requirement_normalization_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialized_jobs_claim",
        "specialized_evaluation_jobs",
        ["status", "available_at", "priority", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_jobs_company", "specialized_evaluation_jobs", ["company_id"], unique=False
    )
    op.create_index(
        "ix_specialized_jobs_domain", "specialized_evaluation_jobs", ["domain"], unique=False
    )
    op.create_index(
        "ix_specialized_jobs_process", "specialized_evaluation_jobs", ["process_id"], unique=False
    )
    op.create_index(
        "uq_specialized_jobs_active_inputs",
        "specialized_evaluation_jobs",
        [
            "process_id",
            "normalization_run_id",
            "company_id",
            "company_profile_snapshot_id",
            "domain",
        ],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING')"),
    )
    op.create_table(
        "specialized_evaluation_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("normalization_run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_manifest", sa.JSON(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("requirement_count", sa.Integer(), nullable=False),
        sa.Column("evaluated_count", sa.Integer(), nullable=False),
        sa.Column("complies_count", sa.Integer(), nullable=False),
        sa.Column("does_not_comply_count", sa.Integer(), nullable=False),
        sa.Column("partial_count", sa.Integer(), nullable=False),
        sa.Column("unknown_count", sa.Integer(), nullable=False),
        sa.Column("not_applicable_count", sa.Integer(), nullable=False),
        sa.Column("conflicting_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain IN ('LEGAL', 'EXPERIENCE', 'TECHNICAL', 'WORKFORCE', 'DOCUMENTARY', 'GUARANTEE', 'OPERATIONAL', 'ORGANIZATIONAL', 'RISK')",
            name="ck_specialized_runs_domain",
        ),
        sa.CheckConstraint("input_digest ~ '^[a-f0-9]{64}$'", name="ck_specialized_runs_digest"),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELLED')",
            name="ck_specialized_runs_status",
        ),
        sa.CheckConstraint("complies_count >= 0", name="ck_specialized_runs_complies_count"),
        sa.CheckConstraint("conflicting_count >= 0", name="ck_specialized_runs_conflicting_count"),
        sa.CheckConstraint(
            "does_not_comply_count >= 0", name="ck_specialized_runs_does_not_comply_count"
        ),
        sa.CheckConstraint("evaluated_count >= 0", name="ck_specialized_runs_evaluated_count"),
        sa.CheckConstraint(
            "not_applicable_count >= 0", name="ck_specialized_runs_not_applicable_count"
        ),
        sa.CheckConstraint("partial_count >= 0", name="ck_specialized_runs_partial_count"),
        sa.CheckConstraint("requirement_count >= 0", name="ck_specialized_runs_requirement_count"),
        sa.CheckConstraint("unknown_count >= 0", name="ck_specialized_runs_unknown_count"),
        sa.CheckConstraint("warning_count >= 0", name="ck_specialized_runs_warning_count"),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["company_profile_snapshot_id"], ["company_profile_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["specialized_evaluation_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["normalization_run_id"], ["requirement_normalization_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialized_runs_domain", "specialized_evaluation_runs", ["domain"], unique=False
    )
    op.create_index(
        "ix_specialized_runs_inputs",
        "specialized_evaluation_runs",
        ["process_id", "input_digest"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_runs_process_company",
        "specialized_evaluation_runs",
        ["process_id", "company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_runs_snapshot",
        "specialized_evaluation_runs",
        ["company_profile_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "specialized_requirement_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("normalization_run_id", sa.Uuid(), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("rule_type", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=True),
        sa.Column("operator", sa.String(length=64), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column("expected_min_value", sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column("expected_max_value", sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("period_policy", sa.String(length=64), nullable=True),
        sa.Column("condition_group", sa.JSON(), nullable=False),
        sa.Column("source_basis", sa.String(length=64), nullable=False),
        sa.Column("mapping_status", sa.String(length=32), nullable=False),
        sa.Column("mapping_warnings", sa.JSON(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("manual_override_payload", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_manual_override", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain IN ('LEGAL', 'EXPERIENCE', 'TECHNICAL', 'WORKFORCE', 'DOCUMENTARY', 'GUARANTEE', 'OPERATIONAL', 'ORGANIZATIONAL', 'RISK')",
            name="ck_specialized_rules_domain",
        ),
        sa.CheckConstraint(
            "mapping_status IN ('MAPPED', 'PARTIALLY_MAPPED', 'AMBIGUOUS', 'UNSUPPORTED', 'INVALID')",
            name="ck_specialized_rules_mapping_status",
        ),
        sa.CheckConstraint(
            "operator IS NULL OR operator IN ('EXISTS', 'NOT_EXISTS', 'EQUAL', 'NOT_EQUAL', 'CONTAINS', 'GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'BETWEEN_INCLUSIVE', 'IN_SET', 'ALL_OF', 'ANY_OF')",
            name="ck_specialized_rules_operator",
        ),
        sa.CheckConstraint(
            "rule_type IN ('DOCUMENT_EXISTS', 'REGISTRATION_EXISTS', 'REGISTRATION_VALID', 'CERTIFICATION_EXISTS', 'CERTIFICATION_VALID', 'EXPERIENCE_EXISTS', 'EXPERIENCE_COUNT', 'EXPERIENCE_VALUE', 'EXPERIENCE_DURATION', 'EXPERIENCE_UNSPSC', 'EXPERIENCE_ACTIVITY', 'PERSON_ROLE_EXISTS', 'PERSON_CREDENTIAL_EXISTS', 'PERSON_EXPERIENCE_YEARS', 'CAPABILITY_EXISTS', 'CAPABILITY_VALUE', 'COVERAGE_EXISTS', 'COMPOSITE_ALL', 'COMPOSITE_ANY', 'INFORMATIONAL', 'UNSUPPORTED')",
            name="ck_specialized_rules_type",
        ),
        sa.CheckConstraint(
            "source_basis IN ('EXPLICIT_EXPECTED_VALUE', 'EXPLICIT_DESCRIPTION', 'MANUAL_OVERRIDE', 'UNKNOWN')",
            name="ck_specialized_rules_source_basis",
        ),
        sa.CheckConstraint("version > 0", name="ck_specialized_rules_version"),
        sa.ForeignKeyConstraint(
            ["normalization_run_id"], ["requirement_normalization_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialized_rules_normalization",
        "specialized_requirement_rules",
        ["normalization_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_rules_requirement",
        "specialized_requirement_rules",
        ["requirement_id", "domain"],
        unique=False,
    )
    op.create_table(
        "specialized_evaluation_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["specialized_evaluation_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["run_id"], ["specialized_evaluation_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialized_events_job_id", "specialized_evaluation_events", ["job_id"], unique=False
    )
    op.create_index(
        "ix_specialized_events_run_id", "specialized_evaluation_events", ["run_id"], unique=False
    )
    op.create_index(
        "ix_specialized_events_type", "specialized_evaluation_events", ["event_type"], unique=False
    )
    op.create_table(
        "specialized_evaluation_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("specialized_rule_id", sa.Uuid(), nullable=True),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("rule_type", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=True),
        sa.Column("operator", sa.String(length=64), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column("actual_value", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("source_record_type", sa.String(length=64), nullable=True),
        sa.Column("source_record_id", sa.Uuid(), nullable=True),
        sa.Column("explanation_code", sa.String(length=64), nullable=False),
        sa.Column("explanation_parameters", sa.JSON(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("reviewed_status", sa.String(length=64), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "domain IN ('LEGAL', 'EXPERIENCE', 'TECHNICAL', 'WORKFORCE', 'DOCUMENTARY', 'GUARANTEE', 'OPERATIONAL', 'ORGANIZATIONAL', 'RISK')",
            name="ck_specialized_results_domain",
        ),
        sa.CheckConstraint(
            "operator IS NULL OR operator IN ('EXISTS', 'NOT_EXISTS', 'EQUAL', 'NOT_EQUAL', 'CONTAINS', 'GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'BETWEEN_INCLUSIVE', 'IN_SET', 'ALL_OF', 'ANY_OF')",
            name="ck_specialized_results_operator",
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING', 'CONFIRMED', 'OVERRIDDEN', 'REJECTED')",
            name="ck_specialized_results_review_status",
        ),
        sa.CheckConstraint(
            "rule_type IN ('DOCUMENT_EXISTS', 'REGISTRATION_EXISTS', 'REGISTRATION_VALID', 'CERTIFICATION_EXISTS', 'CERTIFICATION_VALID', 'EXPERIENCE_EXISTS', 'EXPERIENCE_COUNT', 'EXPERIENCE_VALUE', 'EXPERIENCE_DURATION', 'EXPERIENCE_UNSPSC', 'EXPERIENCE_ACTIVITY', 'PERSON_ROLE_EXISTS', 'PERSON_CREDENTIAL_EXISTS', 'PERSON_EXPERIENCE_YEARS', 'CAPABILITY_EXISTS', 'CAPABILITY_VALUE', 'COVERAGE_EXISTS', 'COMPOSITE_ALL', 'COMPOSITE_ANY', 'INFORMATIONAL', 'UNSUPPORTED')",
            name="ck_specialized_results_rule_type",
        ),
        sa.CheckConstraint(
            "status IN ('COMPLIES', 'DOES_NOT_COMPLY', 'PARTIAL', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING_EVIDENCE')",
            name="ck_specialized_results_status",
        ),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["specialized_evaluation_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["specialized_rule_id"], ["specialized_requirement_rules.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "requirement_id", name="uq_specialized_results_run_requirement"
        ),
    )
    op.create_index(
        "ix_specialized_results_domain", "specialized_evaluation_results", ["domain"], unique=False
    )
    op.create_index(
        "ix_specialized_results_requirement_id",
        "specialized_evaluation_results",
        ["requirement_id"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_results_review",
        "specialized_evaluation_results",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_results_run_id", "specialized_evaluation_results", ["run_id"], unique=False
    )
    op.create_index(
        "ix_specialized_results_status", "specialized_evaluation_results", ["status"], unique=False
    )
    op.create_table(
        "specialized_evaluation_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("company_evidence_link_id", sa.Uuid(), nullable=True),
        sa.Column("company_evidence_document_id", sa.Uuid(), nullable=True),
        sa.Column("requirement_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("extracted_segment_id", sa.Uuid(), nullable=True),
        sa.Column("quoted_text", sa.Text(), nullable=True),
        sa.Column("source_location", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "validation_status IN ('VERIFIED', 'SUPPORTED', 'DECLARED_ONLY', 'EXPIRED', 'REJECTED', 'CONFLICTING', 'MISSING')",
            name="ck_specialized_evidence_validation",
        ),
        sa.ForeignKeyConstraint(
            ["result_id"], ["specialized_evaluation_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialized_evidence_document",
        "specialized_evaluation_evidence",
        ["company_evidence_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_evidence_result",
        "specialized_evaluation_evidence",
        ["result_id"],
        unique=False,
    )
    op.create_table(
        "specialized_evaluation_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("result_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("original_status", sa.String(length=64), nullable=False),
        sa.Column("reviewed_status", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reviewer", sa.String(length=128), nullable=False),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('CONFIRM', 'OVERRIDE', 'REJECT')", name="ck_specialized_reviews_action"
        ),
        sa.CheckConstraint(
            "original_status IN ('COMPLIES', 'DOES_NOT_COMPLY', 'PARTIAL', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING_EVIDENCE')",
            name="ck_specialized_reviews_original_status",
        ),
        sa.CheckConstraint(
            "reviewed_status IS NULL OR reviewed_status IN ('COMPLIES', 'DOES_NOT_COMPLY', 'PARTIAL', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING_EVIDENCE')",
            name="ck_specialized_reviews_reviewed_status",
        ),
        sa.ForeignKeyConstraint(
            ["result_id"], ["specialized_evaluation_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_specialized_reviews_result_id",
        "specialized_evaluation_reviews",
        ["result_id"],
        unique=False,
    )
    op.create_index(
        "ix_specialized_reviews_reviewed_at",
        "specialized_evaluation_reviews",
        ["reviewed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_specialized_reviews_reviewed_at", table_name="specialized_evaluation_reviews")
    op.drop_index("ix_specialized_reviews_result_id", table_name="specialized_evaluation_reviews")
    op.drop_table("specialized_evaluation_reviews")
    op.drop_index("ix_specialized_evidence_result", table_name="specialized_evaluation_evidence")
    op.drop_index("ix_specialized_evidence_document", table_name="specialized_evaluation_evidence")
    op.drop_table("specialized_evaluation_evidence")
    op.drop_index("ix_specialized_results_status", table_name="specialized_evaluation_results")
    op.drop_index("ix_specialized_results_run_id", table_name="specialized_evaluation_results")
    op.drop_index("ix_specialized_results_review", table_name="specialized_evaluation_results")
    op.drop_index(
        "ix_specialized_results_requirement_id", table_name="specialized_evaluation_results"
    )
    op.drop_index("ix_specialized_results_domain", table_name="specialized_evaluation_results")
    op.drop_table("specialized_evaluation_results")
    op.drop_index("ix_specialized_events_type", table_name="specialized_evaluation_events")
    op.drop_index("ix_specialized_events_run_id", table_name="specialized_evaluation_events")
    op.drop_index("ix_specialized_events_job_id", table_name="specialized_evaluation_events")
    op.drop_table("specialized_evaluation_events")
    op.drop_index("ix_specialized_rules_requirement", table_name="specialized_requirement_rules")
    op.drop_index("ix_specialized_rules_normalization", table_name="specialized_requirement_rules")
    op.drop_table("specialized_requirement_rules")
    op.drop_index("ix_specialized_runs_snapshot", table_name="specialized_evaluation_runs")
    op.drop_index("ix_specialized_runs_process_company", table_name="specialized_evaluation_runs")
    op.drop_index("ix_specialized_runs_inputs", table_name="specialized_evaluation_runs")
    op.drop_index("ix_specialized_runs_domain", table_name="specialized_evaluation_runs")
    op.drop_table("specialized_evaluation_runs")
    op.drop_index(
        "uq_specialized_jobs_active_inputs",
        table_name="specialized_evaluation_jobs",
        postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING')"),
    )
    op.drop_index("ix_specialized_jobs_process", table_name="specialized_evaluation_jobs")
    op.drop_index("ix_specialized_jobs_domain", table_name="specialized_evaluation_jobs")
    op.drop_index("ix_specialized_jobs_company", table_name="specialized_evaluation_jobs")
    op.drop_index("ix_specialized_jobs_claim", table_name="specialized_evaluation_jobs")
    op.drop_table("specialized_evaluation_jobs")
    op.drop_constraint("ck_decision_findings_source_type", "decision_input_findings", type_="check")
    op.create_check_constraint(
        "ck_decision_findings_source_type",
        "decision_input_findings",
        "source_type IN ('FINANCIAL_EVALUATION', 'SYNTHETIC', 'MISSING_ADAPTER')",
    )
    # ### end Alembic commands ###
