"""company profile evidence.

Revision ID: 20260702_0004
Revises: 20260702_0003
Create Date: 2026-07-02 20:08:18.608154
"""

# ruff: noqa: E501

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260702_0004"
down_revision: str | None = "20260702_0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("system_process_id", sa.Uuid(), nullable=False),
        sa.Column("internal_reference", sa.String(length=64), nullable=False),
        sa.Column("legal_name", sa.String(length=500), nullable=False),
        sa.Column("trade_name", sa.String(length=500), nullable=True),
        sa.Column("tax_id", sa.String(length=128), nullable=True),
        sa.Column("tax_id_type", sa.String(length=64), nullable=True),
        sa.Column("company_type", sa.String(length=128), nullable=True),
        sa.Column("legal_nature", sa.String(length=128), nullable=True),
        sa.Column("incorporation_date", sa.Date(), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("website", sa.String(length=2083), nullable=True),
        sa.Column("primary_email", sa.String(length=320), nullable=True),
        sa.Column("primary_phone", sa.String(length=128), nullable=True),
        sa.Column("economic_activity_codes", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("btrim(legal_name) <> ''", name="ck_company_profiles_legal_name"),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'INCOMPLETE', 'READY_FOR_REVIEW', 'ARCHIVED')",
            name="ck_company_profiles_status",
        ),
        sa.ForeignKeyConstraint(["system_process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("system_process_id"),
        sa.UniqueConstraint("tax_id_type", "tax_id", name="uq_company_profiles_tax_id"),
    )
    op.create_index(
        "ix_company_profiles_internal_reference",
        "company_profiles",
        ["internal_reference"],
        unique=True,
    )
    op.create_index("ix_company_profiles_status", "company_profiles", ["status"], unique=False)
    op.create_index("ix_company_profiles_tax_id", "company_profiles", ["tax_id"], unique=False)
    op.create_table(
        "company_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("snapshot_version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_audit_events_company_id", "company_audit_events", ["company_id"], unique=False
    )
    op.create_table(
        "company_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("value", sa.String(length=500), nullable=True),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("territorial_scope", sa.String(length=500), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('TECHNOLOGY', 'INFRASTRUCTURE', 'GEOGRAPHIC_COVERAGE', 'OPERATIONAL', 'SERVICE_CAPACITY', 'PLATFORM', 'SECURITY', 'QUALITY', 'OTHER')",
            name="ck_company_capabilities_category",
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_capabilities_status",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_capabilities_company_id", "company_capabilities", ["company_id"], unique=False
    )
    op.create_table(
        "company_certifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("certification_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=True),
        sa.Column("certificate_number", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "certification_type IN ('ISO', 'QUALITY', 'SECURITY', 'CLOUD_PARTNER', 'MANUFACTURER_PARTNER', 'GOVERNMENT_REGISTRY', 'INDUSTRY', 'OTHER')",
            name="ck_company_certifications_type",
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_certifications_status",
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR issued_at IS NULL OR expires_at >= issued_at",
            name="ck_company_certifications_dates",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_certifications_company_id",
        "company_certifications",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_evidence_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("process_document_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_type IN ('RUT', 'CHAMBER_CERTIFICATE', 'RUP', 'FINANCIAL_STATEMENT', 'TAX_RETURN', 'EXPERIENCE_CERTIFICATE', 'CONTRACT', 'ACT_START', 'COMPLETION_CERTIFICATE', 'LIQUIDATION_RECORD', 'CV', 'DIPLOMA', 'PROFESSIONAL_LICENSE', 'PERSON_CERTIFICATION', 'COMPANY_CERTIFICATION', 'INSURANCE', 'UNSPSC_SUPPORT', 'OTHER')",
            name="ck_company_evidence_documents_type",
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_evidence_documents_review_status",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["process_document_id"], ["process_documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "process_document_id", name="uq_company_evidence_document"
        ),
        sa.UniqueConstraint("company_id", "sha256", name="uq_company_evidence_sha256"),
    )
    op.create_index(
        "ix_company_evidence_documents_company_id",
        "company_evidence_documents",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_experience_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("contract_reference", sa.String(length=255), nullable=True),
        sa.Column("contracting_party", sa.String(length=500), nullable=False),
        sa.Column("contract_title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("sector", sa.String(length=255), nullable=True),
        sa.Column("contract_type", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("execution_status", sa.String(length=64), nullable=False),
        sa.Column("total_contract_value", sa.Numeric(precision=28, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "company_participation_percentage", sa.Numeric(precision=6, scale=3), nullable=True
        ),
        sa.Column("company_attributable_value", sa.Numeric(precision=28, scale=2), nullable=True),
        sa.Column("attributable_value_formula", sa.Text(), nullable=True),
        sa.Column("consortium_name", sa.String(length=500), nullable=True),
        sa.Column("consortium_members", sa.JSON(), nullable=False),
        sa.Column("unspsc_codes", sa.JSON(), nullable=False),
        sa.Column("activities", sa.JSON(), nullable=False),
        sa.Column("scope_tags", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_experience_records_status",
        ),
        sa.CheckConstraint(
            "company_participation_percentage IS NULL OR (company_participation_percentage >= 0 AND company_participation_percentage <= 100)",
            name="ck_company_experience_records_percentage",
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name="ck_company_experience_records_dates",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_experience_records_company_id",
        "company_experience_records",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_financial_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_financial_periods_status",
        ),
        sa.CheckConstraint("period_end >= period_start", name="ck_company_financial_periods_dates"),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_financial_periods_company_id",
        "company_financial_periods",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_legal_registrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("registration_type", sa.String(length=64), nullable=False),
        sa.Column("registration_number", sa.String(length=255), nullable=True),
        sa.Column("issuing_authority", sa.String(length=500), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("declared_data", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "registration_type IN ('RUT', 'CHAMBER_OF_COMMERCE', 'RUP', 'LEGAL_REPRESENTATION', 'TAX_REGISTRATION', 'OTHER')",
            name="ck_company_legal_registrations_type",
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_legal_registrations_status",
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR issued_at IS NULL OR expires_at >= issued_at",
            name="ck_company_legal_registrations_dates",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_legal_registrations_company_id",
        "company_legal_registrations",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_people",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=500), nullable=False),
        sa.Column("identification_type", sa.String(length=64), nullable=True),
        sa.Column("identification_number", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=128), nullable=True),
        sa.Column("relationship_type", sa.String(length=64), nullable=False),
        sa.Column("availability_status", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_people_status",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_company_people_company_id", "company_people", ["company_id"], unique=False)
    op.create_table(
        "company_profile_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("completeness_status", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("digest ~ '^[a-f0-9]{64}$'", name="ck_company_profile_snapshots_digest"),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'SUPERSEDED')",
            name="ck_company_profile_snapshots_status",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "version", name="uq_company_profile_snapshots_version"),
    )
    op.create_index(
        "ix_company_profile_snapshots_company_id",
        "company_profile_snapshots",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "company_unspsc_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(code) <> ''", name="ck_company_unspsc_codes_code"),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_unspsc_codes_status",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "code", "valid_until", name="uq_company_unspsc_codes_code"
        ),
    )
    op.create_index(
        "ix_company_unspsc_codes_company_id", "company_unspsc_codes", ["company_id"], unique=False
    )
    op.create_table(
        "rup_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("registration_number", sa.String(length=255), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("renewal_year", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("financial_period_reference", sa.String(length=255), nullable=True),
        sa.Column("organization_capacity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("technical_capacity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("financial_capacity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("experience_capacity", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("raw_declared_data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_rup_snapshots_status",
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR issued_at IS NULL OR valid_until >= issued_at",
            name="ck_rup_snapshots_dates",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rup_snapshots_company_id", "rup_snapshots", ["company_id"], unique=False)
    op.create_table(
        "company_financial_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("financial_period_id", sa.Uuid(), nullable=False),
        sa.Column("metric_type", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("source_value", sa.String(length=500), nullable=True),
        sa.Column("is_calculated", sa.Boolean(), nullable=False),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.Column("formula_inputs", sa.JSON(), nullable=False),
        sa.Column("calculation_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DECLARED', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_financial_metrics_status",
        ),
        sa.ForeignKeyConstraint(
            ["financial_period_id"], ["company_financial_periods.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_financial_metrics_period_id",
        "company_financial_metrics",
        ["financial_period_id"],
        unique=False,
    )
    op.create_table(
        "person_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("credential_type", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("issuer", sa.String(length=500), nullable=True),
        sa.Column("credential_number", sa.String(length=255), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at IS NULL OR issued_at IS NULL OR expires_at >= issued_at",
            name="ck_person_credentials_dates",
        ),
        sa.ForeignKeyConstraint(["person_id"], ["company_people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person_education",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("degree_type", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("institution", sa.String(length=500), nullable=True),
        sa.Column("graduation_date", sa.Date(), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["person_id"], ["company_people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person_experience",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("organization", sa.String(length=500), nullable=False),
        sa.Column("role", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name="ck_person_experience_dates",
        ),
        sa.ForeignKeyConstraint(["person_id"], ["company_people.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_evidence_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=True),
        sa.Column("segment_id", sa.Uuid(), nullable=True),
        sa.Column("evidence_role", sa.String(length=32), nullable=False),
        sa.Column("quoted_text", sa.Text(), nullable=True),
        sa.Column("source_location", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=64), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_role IN ('PRIMARY', 'SUPPORTING', 'CONFLICTING')",
            name="ck_company_evidence_links_role",
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING', 'SUPPORTED', 'VERIFIED', 'REJECTED', 'EXPIRED', 'NEEDS_REVIEW')",
            name="ck_company_evidence_links_review_status",
        ),
        sa.CheckConstraint(
            "subject_type IN ('COMPANY_PROFILE', 'LEGAL_REGISTRATION', 'RUP_SNAPSHOT', 'UNSPSC_CODE', 'FINANCIAL_PERIOD', 'FINANCIAL_METRIC', 'EXPERIENCE_RECORD', 'PERSON', 'PERSON_EDUCATION', 'PERSON_EXPERIENCE', 'PERSON_CREDENTIAL', 'COMPANY_CERTIFICATION', 'COMPANY_CAPABILITY')",
            name="ck_company_evidence_links_subject_type",
        ),
        sa.CheckConstraint(
            "validation_status IN ('DOCUMENT_ONLY', 'VALID_SEGMENT', 'INVALID_SEGMENT', 'QUOTE_NOT_FOUND', 'LOCATION_MISMATCH', 'EXPIRED_EVIDENCE')",
            name="ck_company_evidence_links_validation_status",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["company_evidence_documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["document_extractions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["segment_id"], ["extracted_segments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_evidence_links_company_id",
        "company_evidence_links",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_company_evidence_links_subject",
        "company_evidence_links",
        ["subject_type", "subject_id"],
        unique=False,
    )
    op.add_column(
        "processes",
        sa.Column("is_system", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.alter_column("processes", "is_system", server_default=None)
    op.create_index("ix_processes_is_system", "processes", ["is_system"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_processes_is_system", table_name="processes")
    op.drop_column("processes", "is_system")
    op.drop_index("ix_company_evidence_links_subject", table_name="company_evidence_links")
    op.drop_index("ix_company_evidence_links_company_id", table_name="company_evidence_links")
    op.drop_table("company_evidence_links")
    op.drop_table("person_experience")
    op.drop_table("person_education")
    op.drop_table("person_credentials")
    op.drop_index("ix_company_financial_metrics_period_id", table_name="company_financial_metrics")
    op.drop_table("company_financial_metrics")
    op.drop_index("ix_rup_snapshots_company_id", table_name="rup_snapshots")
    op.drop_table("rup_snapshots")
    op.drop_index("ix_company_unspsc_codes_company_id", table_name="company_unspsc_codes")
    op.drop_table("company_unspsc_codes")
    op.drop_index("ix_company_profile_snapshots_company_id", table_name="company_profile_snapshots")
    op.drop_table("company_profile_snapshots")
    op.drop_index("ix_company_people_company_id", table_name="company_people")
    op.drop_table("company_people")
    op.drop_index(
        "ix_company_legal_registrations_company_id", table_name="company_legal_registrations"
    )
    op.drop_table("company_legal_registrations")
    op.drop_index("ix_company_financial_periods_company_id", table_name="company_financial_periods")
    op.drop_table("company_financial_periods")
    op.drop_index(
        "ix_company_experience_records_company_id", table_name="company_experience_records"
    )
    op.drop_table("company_experience_records")
    op.drop_index(
        "ix_company_evidence_documents_company_id", table_name="company_evidence_documents"
    )
    op.drop_table("company_evidence_documents")
    op.drop_index("ix_company_certifications_company_id", table_name="company_certifications")
    op.drop_table("company_certifications")
    op.drop_index("ix_company_capabilities_company_id", table_name="company_capabilities")
    op.drop_table("company_capabilities")
    op.drop_index("ix_company_audit_events_company_id", table_name="company_audit_events")
    op.drop_table("company_audit_events")
    op.drop_index("ix_company_profiles_tax_id", table_name="company_profiles")
    op.drop_index("ix_company_profiles_status", table_name="company_profiles")
    op.drop_index("ix_company_profiles_internal_reference", table_name="company_profiles")
    op.drop_table("company_profiles")
    # ### end Alembic commands ###
