"""notification delivery outbox.

Revision ID: 20260714_0023
Revises: 20260714_0022
Create Date: 2026-07-14 19:58:44.107168
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260714_0023"
down_revision: str | None = "20260714_0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_destinations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_actor_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("email_address", sa.String(length=320), nullable=True),
        sa.Column("webhook_url", sa.String(length=2083), nullable=True),
        sa.Column("webhook_host", sa.String(length=255), nullable=True),
        sa.Column("secret_reference", sa.String(length=128), nullable=True),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_status", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('INTERNAL_ONLY','EMAIL_SMTP','SIGNED_WEBHOOK')",
            name="ck_notification_destination_channel",
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PAUSED','DISABLED','ERROR','PENDING_VERIFICATION')",
            name="ck_notification_destination_status",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_actor_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_destination_owner",
        "notification_destinations",
        ["owner_actor_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_operation_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_operation_entity",
        "notification_operation_events",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_suppressions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_value", sa.String(length=500), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_digest_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_actor_id", sa.Uuid(), nullable=True),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("alert_count", sa.Integer(), nullable=False),
        sa.Column("outbox_message_id", sa.Uuid(), nullable=True),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["notification_destinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_actor_id"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "destination_id",
            "period",
            "period_start",
            "period_end",
            name="uq_notification_digest_period",
        ),
    )
    op.create_table(
        "notification_subscriptions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_actor_id", sa.Uuid(), nullable=True),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("delivery_mode", sa.String(length=32), nullable=False),
        sa.Column("minimum_severity", sa.String(length=16), nullable=False),
        sa.Column("alert_types", sa.JSON(), nullable=False),
        sa.Column("quiet_hours", sa.JSON(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("daily_digest_time", sa.String(length=5), nullable=False),
        sa.Column("weekly_digest_day", sa.Integer(), nullable=False),
        sa.Column("include_summary", sa.Boolean(), nullable=False),
        sa.Column("include_opportunity_link", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_mode IN ('IMMEDIATE','DAILY_DIGEST','WEEKLY_DIGEST','INTERNAL_ONLY')",
            name="ck_notification_subscription_mode",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["notification_destinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["monitor_id"], ["opportunity_monitors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_actor_id"], ["auth_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_subscription_monitor",
        "notification_subscriptions",
        ["monitor_id", "enabled"],
        unique=False,
    )
    op.create_index(
        "ix_notification_subscription_owner",
        "notification_subscriptions",
        ["owner_actor_id", "enabled"],
        unique=False,
    )
    op.create_table(
        "notification_outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("destination_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("delivery_mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("template_version", sa.String(length=32), nullable=False),
        sa.Column("template_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_class", sa.String(length=32), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','PROCESSING','DELIVERED','FAILED_RETRYABLE',"
            "'FAILED_PERMANENT','CANCELLED','SUPPRESSED','DRY_RUN')",
            name="ck_notification_outbox_status",
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["opportunity_alerts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["notification_destinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["notification_subscriptions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_notification_outbox_idempotency"),
    )
    op.create_index(
        "ix_notification_outbox_alert",
        "notification_outbox_messages",
        ["alert_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_claim",
        "notification_outbox_messages",
        ["status", "available_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_delivered",
        "notification_outbox_messages",
        ["delivered_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_destination",
        "notification_outbox_messages",
        ["destination_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notification_delivery_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("outbox_message_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("smtp_response_code", sa.Integer(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_class", sa.String(length=32), nullable=True),
        sa.Column("error_message_sanitized", sa.String(length=500), nullable=True),
        sa.Column("response_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["outbox_message_id"], ["notification_outbox_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "outbox_message_id", "attempt_number", name="uq_notification_attempt_number"
        ),
    )
    op.create_index(
        "ix_notification_attempt_created",
        "notification_delivery_attempts",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_attempt_created", table_name="notification_delivery_attempts")
    op.drop_table("notification_delivery_attempts")
    op.drop_index("ix_notification_outbox_destination", table_name="notification_outbox_messages")
    op.drop_index("ix_notification_outbox_delivered", table_name="notification_outbox_messages")
    op.drop_index("ix_notification_outbox_claim", table_name="notification_outbox_messages")
    op.drop_index("ix_notification_outbox_alert", table_name="notification_outbox_messages")
    op.drop_table("notification_outbox_messages")
    op.drop_index("ix_notification_subscription_owner", table_name="notification_subscriptions")
    op.drop_index("ix_notification_subscription_monitor", table_name="notification_subscriptions")
    op.drop_table("notification_subscriptions")
    op.drop_table("notification_digest_runs")
    op.drop_table("notification_suppressions")
    op.drop_index("ix_notification_operation_entity", table_name="notification_operation_events")
    op.drop_table("notification_operation_events")
    op.drop_index("ix_notification_destination_owner", table_name="notification_destinations")
    op.drop_table("notification_destinations")
    # ### end Alembic commands ###
