"""opportunity compatibility inbox.

Revision ID: 20260713_0020
Revises: 20260713_0019
Create Date: 2026-07-13 23:01:32.059546
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260713_0020"
down_revision: str | None = "20260713_0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_discovery_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("company_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("source_systems", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("assessed_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSING', 'COMPLETED', "
            "'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELLED')",
            name="ck_opportunity_discovery_status",
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"], ["company_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["company_snapshot_id"], ["company_profile_snapshots.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_discovery_claim",
        "opportunity_discovery_runs",
        ["status", "available_at", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_discovery_digest",
        "opportunity_discovery_runs",
        ["input_digest"],
        unique=False,
    )
    op.create_table(
        "opportunity_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discovery_run_id", sa.Uuid(), nullable=False),
        sa.Column("external_search_result_id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.Uuid(), nullable=True),
        sa.Column("source_system", sa.String(length=32), nullable=False),
        sa.Column("source_process_id", sa.String(length=500), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("entity_name", sa.String(length=500), nullable=False),
        sa.Column("modality", sa.String(length=500), nullable=True),
        sa.Column("source_status", sa.String(length=500), nullable=True),
        sa.Column("publication_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("department", sa.String(length=300), nullable=True),
        sa.Column("municipality", sa.String(length=300), nullable=True),
        sa.Column("document_status", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"], ["opportunity_discovery_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["external_search_result_id"],
            ["external_procurement_search_results.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "discovery_run_id",
            "external_search_result_id",
            name="uq_opportunity_candidate_run_result",
        ),
    )
    op.create_index(
        "ix_opportunity_candidate_source",
        "opportunity_candidates",
        ["source_system", "source_process_id"],
        unique=False,
    )
    op.create_table(
        "opportunity_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("company_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("analysis_level", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("compatibility_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("urgency_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("information_completeness", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("days_remaining", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("urgency_status", sa.String(length=32), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("missing_information", sa.JSON(), nullable=False),
        sa.Column("partner_reasons", sa.JSON(), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_level IN ('METADATA_SCREENING', 'DOCUMENT_SCREENING', 'DEEP_ANALYSIS')",
            name="ck_opportunity_assessment_level",
        ),
        sa.CheckConstraint(
            "outcome IN ('REVISAR_PRIMERO', 'OPORTUNIDAD_POTENCIAL', "
            "'REQUIERE_ALIADO', 'INFORMACION_INSUFICIENTE', "
            "'POCO_COMPATIBLE', 'DESCARTAR')",
            name="ck_opportunity_assessment_outcome",
        ),
        sa.CheckConstraint(
            "urgency_status IN ('CLOSED', 'EXPIRED', 'CRITICAL', 'URGENT', "
            "'NORMAL', 'LONG_HORIZON', 'UNKNOWN')",
            name="ck_opportunity_assessment_urgency",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["opportunity_candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["company_snapshot_id"], ["company_profile_snapshots.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_assessment_candidate",
        "opportunity_assessments",
        ["candidate_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_assessment_digest",
        "opportunity_assessments",
        ["input_digest"],
        unique=False,
    )
    op.create_table(
        "opportunity_assessment_components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("weighted_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("explanation_parameters", sa.JSON(), nullable=False),
        sa.Column("evidence_refs", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "component IN ('RELEVANCE', 'UNSPSC_MATCH', 'EXPERIENCE_MATCH', "
            "'FINANCIAL_FIT', 'TECHNICAL_FIT', 'LEGAL_READINESS', "
            "'GEOGRAPHIC_FIT', 'VALUE_FIT', 'DEADLINE_URGENCY', "
            "'DOCUMENT_READINESS', 'INFORMATION_COMPLETENESS', 'PARTNER_NEED')",
            name="ck_opportunity_component_name",
        ),
        sa.CheckConstraint(
            "status IN ('STRONG_MATCH', 'MATCH', 'PARTIAL_MATCH', 'MISMATCH', "
            "'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING')",
            name="ck_opportunity_component_status",
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["opportunity_assessments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_id", "component", name="uq_opportunity_component"),
    )
    op.create_table(
        "opportunity_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunity_assessments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_event_opportunity",
        "opportunity_events",
        ["opportunity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("previous_action", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('ACKNOWLEDGE', 'SHORTLIST', 'DISMISS', 'SEEK_PARTNER', "
            "'REQUEST_DEEP_ANALYSIS')",
            name="ck_opportunity_review_action",
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["opportunity_assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_review_assessment",
        "opportunity_reviews",
        ["assessment_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_assessment_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_component_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("source_reference", sa.String(length=500), nullable=True),
        sa.Column("excerpt", sa.String(length=1000), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_component_id"],
            ["opportunity_assessment_components.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunity_assessment_evidence")
    op.drop_index("ix_opportunity_review_assessment", table_name="opportunity_reviews")
    op.drop_table("opportunity_reviews")
    op.drop_index("ix_opportunity_event_opportunity", table_name="opportunity_events")
    op.drop_table("opportunity_events")
    op.drop_table("opportunity_assessment_components")
    op.drop_index("ix_opportunity_assessment_digest", table_name="opportunity_assessments")
    op.drop_index("ix_opportunity_assessment_candidate", table_name="opportunity_assessments")
    op.drop_table("opportunity_assessments")
    op.drop_index("ix_opportunity_candidate_source", table_name="opportunity_candidates")
    op.drop_table("opportunity_candidates")
    op.drop_index("ix_opportunity_discovery_digest", table_name="opportunity_discovery_runs")
    op.drop_index("ix_opportunity_discovery_claim", table_name="opportunity_discovery_runs")
    op.drop_table("opportunity_discovery_runs")
    # ### end Alembic commands ###
