"""opportunity monitoring alerts.

Revision ID: 20260714_0021
Revises: 20260713_0020
Create Date: 2026-07-14 00:56:33.235863
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260714_0021"
down_revision: str | None = "20260713_0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_monitors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("company_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("frequency", sa.String(length=32), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("source_systems", sa.JSON(), nullable=False),
        sa.Column("alert_rules", sa.JSON(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("baseline_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "frequency IN ('HOURLY','EVERY_3_HOURS','EVERY_6_HOURS',"
            "'EVERY_12_HOURS','DAILY','WEEKDAYS')",
            name="ck_opportunity_monitor_frequency",
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PAUSED','DISABLED','ERROR')", name="ck_opportunity_monitor_status"
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id"], ["company_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["company_snapshot_id"], ["company_profile_snapshots.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_monitor_due",
        "opportunity_monitors",
        ["status", "next_run_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_monitor_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovery_run_id", sa.Uuid(), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("new_candidate_count", sa.Integer(), nullable=False),
        sa.Column("changed_candidate_count", sa.Integer(), nullable=False),
        sa.Column("alert_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','PROCESSING','COMPLETED','COMPLETED_WITH_WARNINGS',"
            "'FAILED','CANCELLED','SKIPPED')",
            name="ck_opportunity_monitor_run_status",
        ),
        sa.CheckConstraint(
            "trigger_type IN ('SCHEDULED','MANUAL','RETRY','BASELINE')",
            name="ck_opportunity_monitor_run_trigger",
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"], ["opportunity_discovery_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["monitor_id"], ["opportunity_monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitor_id", "input_digest", name="uq_opportunity_monitor_run_digest"),
    )
    op.create_index(
        "ix_opportunity_monitor_run_claim",
        "opportunity_monitor_runs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_opportunity_monitor_active_run",
        "opportunity_monitor_runs",
        ["monitor_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING','PROCESSING')"),
    )
    op.create_table(
        "opportunity_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("monitor_run_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column("assessment_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.String(length=100), nullable=False),
        sa.Column("explanation_parameters", sa.JSON(), nullable=False),
        sa.Column("alert_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_system", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')",
            name="ck_opportunity_alert_severity",
        ),
        sa.CheckConstraint(
            "status IN ('UNREAD','READ','ARCHIVED','RESOLVED')", name="ck_opportunity_alert_status"
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["opportunity_assessments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["monitor_id"], ["opportunity_monitors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["monitor_run_id"], ["opportunity_monitor_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunity_assessments.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alert_fingerprint", name="uq_opportunity_alert_fingerprint"),
    )
    op.create_index(
        "ix_opportunity_alert_inbox", "opportunity_alerts", ["status", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_opportunity_alert_monitor",
        "opportunity_alerts",
        ["monitor_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_monitor_candidate_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("source_system", sa.String(length=32), nullable=False),
        sa.Column("source_process_id", sa.String(length=500), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("compatibility_score", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("urgency_status", sa.String(length=32), nullable=False),
        sa.Column("information_completeness", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("closing_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_state_hash", sa.String(length=64), nullable=False),
        sa.Column("assessment_digest", sa.String(length=64), nullable=False),
        sa.Column("source_status", sa.String(length=500), nullable=True),
        sa.Column("addendum_status", sa.String(length=32), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_alerted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["opportunity_assessments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["monitor_id"], ["opportunity_monitors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunity_assessments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "monitor_id",
            "source_system",
            "source_process_id",
            name="uq_opportunity_monitor_candidate_identity",
        ),
    )
    op.create_index(
        "ix_opportunity_monitor_candidate_seen",
        "opportunity_monitor_candidate_states",
        ["monitor_id", "last_seen_at"],
        unique=False,
    )
    op.create_table(
        "opportunity_alert_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["alert_id"], ["opportunity_alerts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["auth_users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_alert_event_alert",
        "opportunity_alert_events",
        ["alert_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_opportunity_alert_event_alert", table_name="opportunity_alert_events")
    op.drop_table("opportunity_alert_events")
    op.drop_index(
        "ix_opportunity_monitor_candidate_seen", table_name="opportunity_monitor_candidate_states"
    )
    op.drop_table("opportunity_monitor_candidate_states")
    op.drop_index("ix_opportunity_alert_monitor", table_name="opportunity_alerts")
    op.drop_index("ix_opportunity_alert_inbox", table_name="opportunity_alerts")
    op.drop_table("opportunity_alerts")
    op.drop_index(
        "uq_opportunity_monitor_active_run",
        table_name="opportunity_monitor_runs",
        postgresql_where=sa.text("status IN ('PENDING','PROCESSING')"),
    )
    op.drop_index("ix_opportunity_monitor_run_claim", table_name="opportunity_monitor_runs")
    op.drop_table("opportunity_monitor_runs")
    op.drop_index("ix_opportunity_monitor_due", table_name="opportunity_monitors")
    op.drop_table("opportunity_monitors")
    # ### end Alembic commands ###
