"""decision engine.

Revision ID: 20260703_0006
Revises: 20260703_0005
Create Date: 2026-07-02 22:37:41.828101
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260703_0006"
down_revision: str | None = "20260703_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JOB_STATUS_CHECK = (
    "status IN ('PENDING', 'PROCESSING', 'COMPLETED', "
    "'COMPLETED_WITH_WARNINGS', 'FAILED', 'CANCELLED')"
)
DECISION_OUTCOME_CHECK = (
    "'NO_CARGAR', 'NO_GO', 'PENDIENTE_INFORMACION', 'BUSCAR_ALIADO', 'GO_CONDICIONADO', 'GO'"
)
ACTION_TYPE_CHECK = (
    "action_type IN ('PROVIDE_INFORMATION', 'RESOLVE_CONFLICT', "
    "'REVIEW_REQUIREMENT', 'REVIEW_EVIDENCE', 'CORRECT_FINANCIAL_GAP', "
    "'SEEK_PARTNER', 'COMPLETE_MANDATORY_EVALUATION', 'CONFIRM_SUBSANABILITY', "
    "'DO_NOT_SUBMIT', 'OTHER')"
)
FINDING_OUTCOME_CHECK = (
    "outcome IN ('COMPLIES', 'DOES_NOT_COMPLY', 'PARTIAL', 'UNKNOWN', "
    "'NOT_APPLICABLE', 'CONFLICTING_EVIDENCE', 'NOT_EVALUATED')"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_policy_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("policy_name", sa.String(length=128), nullable=False),
        sa.Column("semantic_version", sa.String(length=32), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("policy_payload", sa.JSON(), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("btrim(policy_name) <> ''", name="ck_decision_policy_versions_name"),
        sa.CheckConstraint(
            "content_sha256 ~ '^[a-f0-9]{64}$'", name="ck_decision_policy_versions_hash"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "policy_name", "semantic_version", name="uq_decision_policy_versions_name_version"
        ),
    )
    op.create_index(
        "ix_decision_policy_versions_active",
        "decision_policy_versions",
        ["policy_name", "is_active"],
        unique=False,
    )
    op.create_table(
        "decision_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("normalization_run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("financial_evaluation_run_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("force", sa.Boolean(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            JOB_STATUS_CHECK,
            name="ck_decision_jobs_status",
        ),
        sa.CheckConstraint("attempt_count >= 0", name="ck_decision_jobs_attempts"),
        sa.CheckConstraint("max_attempts > 0", name="ck_decision_jobs_max_attempts"),
        sa.CheckConstraint("priority >= 0", name="ck_decision_jobs_priority"),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["company_profile_snapshot_id"], ["company_profile_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["financial_evaluation_run_id"], ["financial_evaluation_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["normalization_run_id"], ["requirement_normalization_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decision_jobs_claim",
        "decision_jobs",
        ["status", "available_at", "priority", "created_at"],
        unique=False,
    )
    op.create_index("ix_decision_jobs_company", "decision_jobs", ["company_id"], unique=False)
    op.create_index("ix_decision_jobs_process", "decision_jobs", ["process_id"], unique=False)
    op.create_index(
        "uq_decision_jobs_active_inputs",
        "decision_jobs",
        [
            "process_id",
            "normalization_run_id",
            "company_id",
            "company_profile_snapshot_id",
            "financial_evaluation_run_id",
        ],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING')"),
    )
    op.create_table(
        "decision_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("normalization_run_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("financial_evaluation_run_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("engine_outcome", sa.String(length=32), nullable=True),
        sa.Column("reviewed_outcome", sa.String(length=32), nullable=True),
        sa.Column("effective_outcome", sa.String(length=32), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("input_manifest", sa.JSON(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("coverage_summary", sa.JSON(), nullable=False),
        sa.Column("requirement_count", sa.Integer(), nullable=False),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("action_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            f"effective_outcome IS NULL OR effective_outcome IN ({DECISION_OUTCOME_CHECK})",
            name="ck_decision_runs_effective_outcome",
        ),
        sa.CheckConstraint(
            f"engine_outcome IS NULL OR engine_outcome IN ({DECISION_OUTCOME_CHECK})",
            name="ck_decision_runs_engine_outcome",
        ),
        sa.CheckConstraint("input_digest ~ '^[a-f0-9]{64}$'", name="ck_decision_runs_digest"),
        sa.CheckConstraint(
            f"reviewed_outcome IS NULL OR reviewed_outcome IN ({DECISION_OUTCOME_CHECK})",
            name="ck_decision_runs_reviewed_outcome",
        ),
        sa.CheckConstraint(
            JOB_STATUS_CHECK,
            name="ck_decision_runs_status",
        ),
        sa.CheckConstraint("action_count >= 0", name="ck_decision_runs_action_count"),
        sa.CheckConstraint("finding_count >= 0", name="ck_decision_runs_finding_count"),
        sa.CheckConstraint("requirement_count >= 0", name="ck_decision_runs_requirement_count"),
        sa.CheckConstraint("warning_count >= 0", name="ck_decision_runs_warning_count"),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["company_profile_snapshot_id"], ["company_profile_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["financial_evaluation_run_id"], ["financial_evaluation_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["decision_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["normalization_run_id"], ["requirement_normalization_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["policy_version_id"], ["decision_policy_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decision_runs_inputs", "decision_runs", ["process_id", "input_digest"], unique=False
    )
    op.create_index(
        "ix_decision_runs_outcome", "decision_runs", ["effective_outcome"], unique=False
    )
    op.create_index("ix_decision_runs_policy", "decision_runs", ["policy_version_id"], unique=False)
    op.create_index(
        "ix_decision_runs_process_company",
        "decision_runs",
        ["process_id", "company_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_decision_runs_snapshot", "decision_runs", ["company_profile_snapshot_id"], unique=False
    )
    op.create_table(
        "decision_action_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("title_code", sa.String(length=128), nullable=False),
        sa.Column("description_code", sa.String(length=128), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("requirement_ids", sa.JSON(), nullable=False),
        sa.Column("finding_ids", sa.JSON(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            ACTION_TYPE_CHECK,
            name="ck_decision_actions_type",
        ),
        sa.CheckConstraint(
            "priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')", name="ck_decision_actions_priority"
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')",
            name="ck_decision_actions_status",
        ),
        sa.ForeignKeyConstraint(["decision_run_id"], ["decision_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decision_actions_run", "decision_action_items", ["decision_run_id"], unique=False
    )
    op.create_index("ix_decision_actions_status", "decision_action_items", ["status"], unique=False)
    op.create_table(
        "decision_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("process_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["company_profiles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["decision_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["process_id"], ["processes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["decision_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_decision_events_job", "decision_events", ["job_id"], unique=False)
    op.create_index("ix_decision_events_run", "decision_events", ["run_id"], unique=False)
    op.create_index("ix_decision_events_type", "decision_events", ["event_type"], unique=False)
    op.create_table(
        "decision_input_findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_finding_key", sa.String(length=128), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=64), nullable=False),
        sa.Column("modality", sa.String(length=64), nullable=False),
        sa.Column("criticality", sa.String(length=32), nullable=False),
        sa.Column("criticality_basis", sa.String(length=32), nullable=False),
        sa.Column("subsanability", sa.String(length=32), nullable=False),
        sa.Column("subsanability_basis", sa.String(length=32), nullable=False),
        sa.Column("evaluation_domain", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_run_id", sa.Uuid(), nullable=True),
        sa.Column("source_result_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("applicability", sa.String(length=32), nullable=False),
        sa.Column("evidence_quality", sa.String(length=64), nullable=True),
        sa.Column("review_status", sa.String(length=32), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("is_blocking", sa.Boolean(), nullable=False),
        sa.Column("is_remediable", sa.Boolean(), nullable=False),
        sa.Column("partner_solvable", sa.Boolean(), nullable=False),
        sa.Column("submission_blocker", sa.Boolean(), nullable=False),
        sa.Column("condition_codes", sa.JSON(), nullable=False),
        sa.Column("warning_codes", sa.JSON(), nullable=False),
        sa.Column("evidence_references", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applicability IN ('MANDATORY', 'OPTIONAL', 'INFORMATIONAL', 'NOT_APPLICABLE')",
            name="ck_decision_findings_applicability",
        ),
        sa.CheckConstraint(
            FINDING_OUTCOME_CHECK,
            name="ck_decision_findings_outcome",
        ),
        sa.CheckConstraint(
            "source_type IN ('FINANCIAL_EVALUATION', 'SYNTHETIC', 'MISSING_ADAPTER')",
            name="ck_decision_findings_source_type",
        ),
        sa.ForeignKeyConstraint(["decision_run_id"], ["decision_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requirement_id"], ["requirements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "decision_run_id", "source_finding_key", name="uq_decision_findings_run_key"
        ),
    )
    op.create_index(
        "ix_decision_findings_outcome", "decision_input_findings", ["outcome"], unique=False
    )
    op.create_index(
        "ix_decision_findings_requirement",
        "decision_input_findings",
        ["requirement_id"],
        unique=False,
    )
    op.create_index(
        "ix_decision_findings_run", "decision_input_findings", ["decision_run_id"], unique=False
    )
    op.create_table(
        "decision_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("original_outcome", sa.String(length=32), nullable=False),
        sa.Column("reviewed_outcome", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reviewer_reference", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('CONFIRM', 'OVERRIDE', 'REJECT')", name="ck_decision_reviews_action"
        ),
        sa.CheckConstraint(
            f"original_outcome IN ({DECISION_OUTCOME_CHECK})",
            name="ck_decision_reviews_original_outcome",
        ),
        sa.CheckConstraint(
            f"reviewed_outcome IS NULL OR reviewed_outcome IN ({DECISION_OUTCOME_CHECK})",
            name="ck_decision_reviews_reviewed_outcome",
        ),
        sa.ForeignKeyConstraint(["decision_run_id"], ["decision_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_decision_reviews_run", "decision_reviews", ["decision_run_id"], unique=False
    )
    op.create_table(
        "decision_rule_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_run_id", sa.Uuid(), nullable=False),
        sa.Column("rule_code", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("suggested_outcome", sa.String(length=32), nullable=True),
        sa.Column("fact_payload", sa.JSON(), nullable=False),
        sa.Column("requirement_ids", sa.JSON(), nullable=False),
        sa.Column("finding_ids", sa.JSON(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('TRIGGERED', 'NOT_TRIGGERED', 'NOT_APPLICABLE', 'INDETERMINATE')",
            name="ck_decision_rules_status",
        ),
        sa.CheckConstraint(
            f"suggested_outcome IS NULL OR suggested_outcome IN ({DECISION_OUTCOME_CHECK})",
            name="ck_decision_rules_suggested_outcome",
        ),
        sa.ForeignKeyConstraint(["decision_run_id"], ["decision_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_run_id", "rule_code", name="uq_decision_rules_run_code"),
    )
    op.create_index(
        "ix_decision_rules_code", "decision_rule_evaluations", ["rule_code"], unique=False
    )
    op.create_index(
        "ix_decision_rules_run", "decision_rule_evaluations", ["decision_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_decision_rules_run", table_name="decision_rule_evaluations")
    op.drop_index("ix_decision_rules_code", table_name="decision_rule_evaluations")
    op.drop_table("decision_rule_evaluations")
    op.drop_index("ix_decision_reviews_run", table_name="decision_reviews")
    op.drop_table("decision_reviews")
    op.drop_index("ix_decision_findings_run", table_name="decision_input_findings")
    op.drop_index("ix_decision_findings_requirement", table_name="decision_input_findings")
    op.drop_index("ix_decision_findings_outcome", table_name="decision_input_findings")
    op.drop_table("decision_input_findings")
    op.drop_index("ix_decision_events_type", table_name="decision_events")
    op.drop_index("ix_decision_events_run", table_name="decision_events")
    op.drop_index("ix_decision_events_job", table_name="decision_events")
    op.drop_table("decision_events")
    op.drop_index("ix_decision_actions_status", table_name="decision_action_items")
    op.drop_index("ix_decision_actions_run", table_name="decision_action_items")
    op.drop_table("decision_action_items")
    op.drop_index("ix_decision_runs_snapshot", table_name="decision_runs")
    op.drop_index("ix_decision_runs_process_company", table_name="decision_runs")
    op.drop_index("ix_decision_runs_policy", table_name="decision_runs")
    op.drop_index("ix_decision_runs_outcome", table_name="decision_runs")
    op.drop_index("ix_decision_runs_inputs", table_name="decision_runs")
    op.drop_table("decision_runs")
    op.drop_index(
        "uq_decision_jobs_active_inputs",
        table_name="decision_jobs",
        postgresql_where=sa.text("status IN ('PENDING', 'PROCESSING')"),
    )
    op.drop_index("ix_decision_jobs_process", table_name="decision_jobs")
    op.drop_index("ix_decision_jobs_company", table_name="decision_jobs")
    op.drop_index("ix_decision_jobs_claim", table_name="decision_jobs")
    op.drop_table("decision_jobs")
    op.drop_index("ix_decision_policy_versions_active", table_name="decision_policy_versions")
    op.drop_table("decision_policy_versions")
    # ### end Alembic commands ###
